import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  lang: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'nav.home': '首頁',
    'nav.about': '關於我們',
    'nav.services': '美編設計',
    'nav.portfolio': '精選作品',
    'nav.contact': '聯絡我們',
    'hero.title': '穩固基礎，細節致遠',
    'hero.desc': '我們在資訊破碎的時代中，不虛華、不妥協，讓每一個選擇都值得被信賴。',
    'services.title': '美編設計 Graphic Design',
    'services.desc': '德全有限公司提供專業的美編視覺設計服務。從名片設計、Logo設計到廣告文宣，打造專屬您的品牌美感與專業形象。',
    'cart.open': '開啟購物車',
    'cart.view': '查看目前購物車',
    'lang.label': 'EN',
    // About Section
    'about.title': '我們的核心價值',
    'about.value1.title': '極致專注',
    'about.value1.desc': '全心投入每一個環節，以近乎苛求的標準打磨細節，交付經得起時間檢驗的成果。',
    'about.value2.title': '跨界整合',
    'about.value2.desc': '跨域思考，整合資源，為你找到更好的解法。',
    'about.value3.title': '客戶至上',
    'about.value3.desc': '以客戶需求為中心，提供量身定制的解決方案。',
    'about.value4.title': '高效透明',
    'about.value4.desc': '流程透明，溝通高效，確保每個環節都符合客戶期望。',
    // Portfolio Section
    'portfolio.subtitle': 'Featured Works',
    'portfolio.title': '精選作品 Showcase',
    'portfolio.viewDetails': '查看詳情',
    'portfolio.viewProject': '查看作品',
    'portfolio.startProject': '開啟您的專案合作',
    // Contact Section
    'contact.subtitle': '聯絡我們',
    'contact.title': '與我們取得聯繫',
    'contact.desc': '有任何問題或需要更多信息？請填寫下方表單或直接聯絡我們。',
    'contact.hours': '營業時間',
    'contact.hours.24': '24小時',
    'contact.form.name': '姓名 *',
    'contact.form.namePlaceholder': '您的姓名',
    'contact.form.email': '郵箱 *',
    'contact.form.emailPlaceholder': '您的mail',
    'contact.form.phone': '電話',
    'contact.form.phonePlaceholder': '您的電話',
    'contact.form.subject': '主題 *',
    'contact.form.subjectPlaceholder': '消息主題',
    'contact.form.message': '消息 *',
    'contact.form.messagePlaceholder': '請輸入您的消息',
    'contact.form.submit': '發送消息',
    'contact.form.submitting': '發送中...',
    'contact.form.success': '感謝您的消息！我們將盡快回覆您。',
    'contact.label.phone': '電話',
    'contact.label.address': '地址',
    // Footer Section
    'footer.links': '快速連結',
    'footer.contact': '聯絡方式',
    'footer.copyright': '© 德全有限公司 (DEQUAN-M CO.LTD). 版權所有。',
    'footer.privacy': '隱私政策',
    'footer.terms': '服務條款',
    // Categories and Custom Pricing Pages
    'nav.websitepricing': '網站架設',
    'nav.mediamarketing': '精準媒體行銷方案',
    'nav.admin': '管理後台',
    'website.branding': '形象網站',
    'website.shopping': '購物網站',
    'website.blog': '部落格網站',
    'website.onepage': '一頁式網站',
    'website.special': '特殊功能網站',
    'website.fixedshop': '定版式購物網站',
    'media.brandplan': '品牌整體規劃',
    'media.launch': '產品上市規劃',
    'media.celebrity': '明星網紅合作',
    'media.reputation': '輿論口碑操作',
    'media.socialads': '社群行銷投放',
    'media.mediabuy': '媒體採購方案',
    'media.crowdfunding': '募資規劃操盤',
    'media.adspace': '廣告版面',
    'media.pressrelease': '新聞稿撰寫',
    'media.interview': '人物專訪',
    'media.publicrelations': '公關媒體',
    'media.integratedmarketing': '整合行銷',
    'media.grantplan': '政府補助專案',
    'graphic.businesscard': '名片設計',
    'graphic.logodesign': 'Logo設計',
    'graphic.adcopy': '廣告文宣',
    'pricing.backToHome': '返回首頁',
    'pricing.websiteTitle': '網站架設',
    'pricing.websiteDesc': '依您的需求選擇最適合的網站方案，透明報價、專業開發、快速交件。',
    'pricing.marketingTitle': '精準媒體行銷方案',
    'pricing.marketingDesc': '品牌曝光、口碑操作、社群投放…全方位行銷服務，透明報價，彈性組合。',
    'pricing.services': '服務項目',
    'pricing.inquireNow': '立即諮詢',
    'adspace.title': '廣告版面方案',
    'adspace.desc': '選擇最適合您的廣告位置，讓品牌曝光最大化',
    'adspace.backToMarketing': '返回媒體採購方案總覽',
    'adspace.homepage': '首頁廣告版面',
    'adspace.menu': '網站選單廣告版面',
    'adspace.classified': '分類廣告版面',
    'admin.revenue': '本月營收',
    'admin.pendingOrders': '待處理訂單',
    'admin.activeProducts': '上架商品',
    'admin.activeCoupons': '活動折價券',
    'admin.center': '後台管理中心',
    'admin.products': '商品管理',
    'admin.coupons': '折價券管理',
    'admin.orders': '訂單管理',
    'admin.settings': '管理員設定',
    'admin.backToFront': '返回前台',
    'admin.addProduct': '新增商品',
    'admin.addCoupon': '新增折價券',
    'admin.image': '圖片',
    'admin.name': '名稱',
    'admin.category': '分類',
    'admin.price': '價格',
    'admin.action': '操作',
    'admin.code': '代碼',
    'admin.type': '類型',
    'admin.value': '折扣值',
    'admin.minThreshold': '最低門檻',
    'admin.orderId': '訂單編號',
    'admin.time': '時間',
    'admin.recipient': '收件人',
    'admin.detail': '明細',
    'admin.total': '總金額',
    'admin.statusManage': '狀態管理',
    'admin.permissionDescTitle': '管理員權限說明',
    'admin.permissionDesc': '管理員可以操作後台所有功能，包含商品管理、折價券管理、訂單狀態管理。新增管理員後，該帳號登入即可直接使用後台功能。',
    'admin.addAdminEmail': '新增管理員 Email',
    'admin.addAdminBtn': '新增管理員',
    'admin.addedTime': '新增時間',
    'admin.you': '你',
    'admin.notRemovable': '不可移除',
    'admin.editProduct': '編輯商品',
    'admin.saveProduct': '儲存商品',
    'admin.newCoupon': '新增活動折價券',
    'admin.createCoupon': '建立折價券',
    'admin.desc': '探索日常物件中的美學價值。我們精選具有商業美感與生活溫度的器物，讓您的空間與生活更加精緻。',
    'admin.copyright': '© 2026 Carrot Studio. 版權所有',
    'admin.status.pending': '待處理',
    'admin.status.processing': '處理中',
    'admin.status.shipped': '已出貨',
    'admin.status.completed': '已完成',
    'admin.status.cancelled': '已取消',
    'admin.coupon.fixed': '固定金額',
    'admin.coupon.percent': '百分比',
    'admin.coupon.shipping': '免運費',
    'admin.experience': '後台體驗 (DEMO)',
    'admin.storeOverview': '商店總覽',
    'admin.couponCenter': '領券中心',
    'admin.aboutMiru': '關於卡洛特',
    'nav.account': '帳戶',
    'nav.logout': '登出帳號',
    'nav.login': '會員登入',
    'nav.register': '新用戶註冊',
    'admin.cart': '購物車',
    'admin.items': '項商品',
    'admin.description': '描述',
    'admin.coupon': '活動折價券',
    'admin.deleteProduct': '刪除商品',
    'admin.expiryDate': '失效日期',
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Graphic Design',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    'hero.title': 'Solid Foundation, Distant Details',
    'hero.desc': 'In an era of fragmented information, we are not flashy or compromising, making every choice worthy of trust.',
    'services.title': 'Graphic Design',
    'services.desc': 'DEQUAN-M provides professional graphic design services. From business card and logo design to advertising copy, creating your unique brand aesthetics and professional image.',
    'cart.open': 'Open Cart',
    'cart.view': 'View Cart',
    'lang.label': '中文',
    // About Section
    'about.title': 'Our Core Values',
    'about.value1.title': 'Ultimate Focus',
    'about.value1.desc': 'Fully committed to every detail, polishing with exacting standards to deliver results that stand the test of time.',
    'about.value2.title': 'Cross-Integration',
    'about.value2.desc': 'Thinking across domains and integrating resources to find better solutions for you.',
    'about.value3.title': 'Customer First',
    'about.value3.desc': 'Centering on customer needs to provide tailor-made solutions.',
    'about.value4.title': 'Efficiency & Transparency',
    'about.value4.desc': 'Transparent processes and efficient communication to ensure every step meets expectations.',
    // Portfolio Section
    'portfolio.subtitle': 'Featured Works',
    'portfolio.title': 'Portfolio Showcase',
    'portfolio.viewDetails': 'View Details',
    'portfolio.viewProject': 'View Project',
    'portfolio.startProject': 'Start Your Project',
    // Contact Section
    'contact.subtitle': 'Contact Us',
    'contact.title': 'Get In Touch',
    'contact.desc': 'Have any questions or need more information? Fill out the form below or contact us directly.',
    'contact.hours': 'Business Hours',
    'contact.hours.24': '24 Hours',
    'contact.form.name': 'Name *',
    'contact.form.namePlaceholder': 'Your Name',
    'contact.form.email': 'Email *',
    'contact.form.emailPlaceholder': 'Your Email',
    'contact.form.phone': 'Phone',
    'contact.form.phonePlaceholder': 'Your Phone',
    'contact.form.subject': 'Subject *',
    'contact.form.subjectPlaceholder': 'Message Subject',
    'contact.form.message': 'Message *',
    'contact.form.messagePlaceholder': 'Enter your message',
    'contact.form.submit': 'Send Message',
    'contact.form.submitting': 'Sending...',
    'contact.form.success': 'Thank you for your message! We will get back to you soon.',
    'contact.label.phone': 'Phone',
    'contact.label.address': 'Address',
    // Footer Section
    'footer.links': 'Quick Links',
    'footer.contact': 'Contact Us',
    'footer.copyright': '© DEQUAN-M CO.LTD. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    // Categories and Custom Pricing Pages
    'nav.websitepricing': 'Website Setup',
    'nav.mediamarketing': 'Precision Media Marketing',
    'nav.admin': 'Admin Panel',
    'website.branding': 'Branding Website',
    'website.shopping': 'E-commerce Website',
    'website.blog': 'Blog Website',
    'website.onepage': 'One-page Website',
    'website.special': 'Custom Feature Website',
    'website.fixedshop': 'Fixed-template E-commerce',
    'media.brandplan': 'Brand Strategy Planning',
    'media.launch': 'Product Launch Strategy',
    'media.celebrity': 'Influencer & Celebrity',
    'media.reputation': 'Public Opinion & PR',
    'media.socialads': 'Social Media Advertising',
    'media.mediabuy': 'Media Buying Solutions',
    'media.crowdfunding': 'Crowdfunding Strategy',
    'media.adspace': 'Ad Space',
    'media.pressrelease': 'Press Release',
    'media.interview': 'Interview',
    'media.publicrelations': 'Public Relations',
    'media.integratedmarketing': 'Integrated Marketing',
    'media.grantplan': 'Government Grant Plan',
    'graphic.businesscard': 'Business Card Design',
    'graphic.logodesign': 'Logo Design',
    'graphic.adcopy': 'Ad Copywriting',
    'pricing.backToHome': 'Back to Home',
    'pricing.websiteTitle': 'Website Setup',
    'pricing.websiteDesc': 'Choose the most suitable website solution based on your needs. Transparent pricing, professional development, fast delivery.',
    'pricing.marketingTitle': 'Precision Media Marketing',
    'pricing.marketingDesc': 'Brand exposure, word-of-mouth operation, social media ads... comprehensive marketing services with transparent pricing and flexible packages.',
    'pricing.services': 'Services',
    'pricing.inquireNow': 'Inquire Now',
    'adspace.title': 'Ad Space Solutions',
    'adspace.desc': 'Choose the most suitable ad placement to maximize brand exposure',
    'adspace.backToMarketing': 'Back to Media Buying Overview',
    'adspace.homepage': 'Homepage Ad Space',
    'adspace.menu': 'Menu Ad Space',
    'adspace.classified': 'Classified Ad Space',
    'admin.revenue': 'Monthly Revenue',
    'admin.pendingOrders': 'Pending Orders',
    'admin.activeProducts': 'Active Products',
    'admin.activeCoupons': 'Active Coupons',
    'admin.center': 'Admin Control Center',
    'admin.products': 'Product Management',
    'admin.coupons': 'Coupon Management',
    'admin.orders': 'Order Management',
    'admin.settings': 'Admin Settings',
    'admin.backToFront': 'Back to Front',
    'admin.addProduct': 'Add Product',
    'admin.addCoupon': 'Add Coupon',
    'admin.image': 'Image',
    'admin.name': 'Name',
    'admin.category': 'Category',
    'admin.price': 'Price',
    'admin.action': 'Action',
    'admin.code': 'Code',
    'admin.type': 'Type',
    'admin.value': 'Discount Value',
    'admin.minThreshold': 'Min Threshold',
    'admin.orderId': 'Order ID',
    'admin.time': 'Time',
    'admin.recipient': 'Recipient',
    'admin.detail': 'Detail',
    'admin.total': 'Total Amount',
    'admin.statusManage': 'Status Management',
    'admin.permissionDescTitle': 'Admin Permissions Guidelines',
    'admin.permissionDesc': 'Admins can perform all administrative tasks, including product management, coupon management, and order status updates. Newly added admins can access the control panel immediately after logging in.',
    'admin.addAdminEmail': 'Add Admin Email',
    'admin.addAdminBtn': 'Add Admin',
    'admin.addedTime': 'Date Added',
    'admin.you': 'You',
    'admin.notRemovable': 'Cannot Remove',
    'admin.editProduct': 'Edit Product',
    'admin.saveProduct': 'Save Product',
    'admin.newCoupon': 'New Promo Coupon',
    'admin.createCoupon': 'Create Coupon',
    'admin.desc': 'Explore the aesthetic value of everyday objects. We curate items with commercial aesthetics and life warmth to make your space and life more exquisite.',
    'admin.copyright': '© 2026 Carrot Studio. All rights reserved.',
    'admin.status.pending': 'Pending',
    'admin.status.processing': 'Processing',
    'admin.status.shipped': 'Shipped',
    'admin.status.completed': 'Completed',
    'admin.status.cancelled': 'Cancelled',
    'admin.coupon.fixed': 'Fixed Amount',
    'admin.coupon.percent': 'Percentage',
    'admin.coupon.shipping': 'Free Shipping',
    'admin.experience': 'Admin Demo',
    'admin.storeOverview': 'Store Overview',
    'admin.couponCenter': 'Coupon Center',
    'admin.aboutMiru': 'About Miru',
    'nav.account': 'Account',
    'nav.logout': 'Log Out',
    'nav.login': 'Member Login',
    'nav.register': 'Register',
    'admin.cart': 'Cart',
    'admin.items': 'items',
    'admin.description': 'Description',
    'admin.coupon': 'Coupon',
    'admin.deleteProduct': 'Delete Product',
    'admin.expiryDate': 'Expiry Date',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('zh');

  const toggleLanguage = () => {
    setLang((prev) => (prev === 'zh' ? 'en' : 'zh'));
  };

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
